linters:
  RuboCop:
    enabled: false

exclude:
  - 'app/cells/folio/console/publishable_inputs/show.slim'
  - 'app/views/folio/console/partials/_translations.slim'
  - 'lib/generators/folio/console/scaffold/templates/*'
